#!/bin/bash

# Fixes the symlinks generated by the makefiles. Must be run from the directory you intend to fix.
# So if you want to fix links in ./examples, you must run the script from inside ./examples.
# Don't run this in the root directory. That's a bad idea.

set -o errexit
set -o nounset
set -o noglob
set -o pipefail

find . -type l | while read -r l; do
    target="$(realpath "$l")"
    ln -fs "$(realpath --relative-to="$(dirname "$(realpath -s "$l")")" "$target")" "$l"
done